"""Fixed canvas and overlay render sizes."""

CANVAS_WIDTH = 1400
CANVAS_HEIGHT = 840
CANVAS_SIZE = (CANVAS_WIDTH, CANVAS_HEIGHT)
ASPECT_RATIO = (5, 3)  # 1400:840
OVERLAY_RENDER_SCALE = 2
OVERLAY_RENDER_SIZE = (
    CANVAS_WIDTH * OVERLAY_RENDER_SCALE,
    CANVAS_HEIGHT * OVERLAY_RENDER_SCALE,
)
PNG_COMPRESS_LEVEL = 6

OVERLAY_FILE_VARIANTS = ("overlay", "overlay_ai", "overlay_ai_only")
NO_OVERLAY_VARIANT = "none"
OVERLAY_VARIANTS = (*OVERLAY_FILE_VARIANTS, NO_OVERLAY_VARIANT)
OVERLAY_LABELS = {
    "overlay": "overlay",
    "overlay_ai": "overlay_ai",
    "overlay_ai_only": "overlay_ai_only",
    "none": "no overlay",
}
DEFAULT_OVERLAY_VARIANT = "overlay"

DEFAULT_HEADLINE = "insert your text here"
TEXT_COLOR = (255, 255, 255, 255)
TEXT_SIZE_PX = 96
TEXT_LINE_HEIGHT = 112
TEXT_PADDING_X = 64
TEXT_PADDING_Y = 64
TEXT_FONT_FAMILY = "Gilroy"
TEXT_FONT_WEIGHT = 500

CROP_BOX_COLOR = "#6BCCE0"
PAGE_BACKGROUND = "#AF1E65"
