"""Fixed canvas and overlay render sizes."""

CANVAS_WIDTH = 1400
CANVAS_HEIGHT = 840
CANVAS_SIZE = (CANVAS_WIDTH, CANVAS_HEIGHT)
ASPECT_RATIO = (5, 3)  # 1400:840
OVERLAY_RENDER_SCALE = 2
OVERLAY_RENDER_SIZE = (
    CANVAS_WIDTH * OVERLAY_RENDER_SCALE,
    CANVAS_HEIGHT * OVERLAY_RENDER_SCALE,
)
PNG_COMPRESS_LEVEL = 6

DEFAULT_HEADLINE = "insert your text here"
TEXT_COLOR = (255, 255, 255, 255)
TEXT_SIZE_PX = 80
TEXT_LINE_HEIGHT = 80
TEXT_PADDING_X = 32
TEXT_PADDING_Y = 32
TEXT_FONT_FAMILY = "Gilroy"
TEXT_FONT_WEIGHT = 700

CROP_BOX_COLOR = "#6BCCE0"
PAGE_BACKGROUND = "#AF1E65"
